version: '3'

volumes:
      cms_db: {}
      cms_log: {}
      cms_tasks: {}

services:
    cms:
        container_name: cms
        privileged: yes
        restart: always
        build: cms
        ports:
            - 8888
            - 8889
        volumes:
            - ${PWD}/cms-docker/cms.conf:/usr/local/etc/cms.conf
            - cms_log:/var/local/log/cms/
            - cms_tasks:/problems/
        links:
            - postgres

    postgres:
        restart: always
        image: postgres
        volumes:
            - cms_db:/var/lib/postgresql/data
            - .${PWD}/cms-docker/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
        environment:
            - POSTGRES_DB=cmsdb
            - POSTGRES_USER=cmsuser
            - POSTGRES_PASSWORD=cmspass
