version: '3'

volumes:
      cms_db: {}
      cms_log: {}
      cms_tasks: {}

services:
    cms:
        container_name: cms
        privileged: yes
        restart: always
        build: cms-docker
        ports:
            - "8888:8888"
            - "8889:8889"
            - "9001:9001"
        volumes:
            - cms_log:/var/local/log/cms/
            - cms_tasks:/problems/
            - ./cms-docker/conf:/cms-conf
        environment:
            - CMS_CONFIG=/cms-conf/cms.conf
            - CMS_ADMIN_USERNAME=admin
            - CMS_ADMIN_PASSWORD=nimda
            - SUPERVISOR_ADMIN_USERNAME=admin
            - SUPERVISOR_ADMIN_PASSWORD=admin
        depends_on:
            - "postgres"
        command: ./wait-for-it.sh postgres:5432 -- bash -c "./run-cms.sh"

    postgres:
        restart: always
        image: postgres
        user: postgres
        volumes:
            - cms_db:/var/lib/postgresql/data
            - ${PWD}/cms-docker/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
        environment:
            - POSTGRES_PASSWORD=pa55w0rd
